# Exceptions

Descendants of class Exception are used to communicate between Kernel#raise and rescue statements in begin ... end blocks. Exception objects carry information about the exception – its type (the exception’s class name), an optional descriptive string, and optional traceback information. Exception subclasses may add additional information like NameError#name.

Programs may make subclasses of Exception, typically of StandardError or RuntimeError, to provide custom classes and add additional information. 

### IOError --> Raised when an IO operation fails.
···
File.open("/etc/hosts") {|f| f << "example"}
  #=> IOError: not opened for writing

File.open("/etc/hosts") {|f| f.close; f.read }
  #=> IOError: closed stream
···

NameError --> Raised when a given name is invalid or undefined.
Ej:
puts foo

raises the exception:

NameError: undefined local variable or method `foo' for main:Object

RuntimeError -->
NotImplementedError -->
StopIteration -->
TypeError -->
SystemExit -->
